T.Properties.VariableNames = {'DEVICE' 'FUNCTION' 'DATA_TYPE'... %%DA aggiungere FILE_CSV, PATH
                              'DIFFICULTY_LEVEL' 'DISTINCT_OPERANDS'...
                              'DSTINCT_OPERATORS' 'EFFORT' 'PROGRAM_LENGTH'...
                              'PROGRAM_LEVEL' 'PROGRAM_VOLUME' 'TOTAL_OPERATORS'... 
                              'TOTAL_OPERANDS' 'VOCABULARY_SIZE' 'SLOC' 'DECISIONPOINT'...
                              'GLOBALVARIABLES' 'If' 'LOOP' 'GOTO' 'ASSIGNMENT' 'EXITPOINT'...
                              'Function' 'FUNCTIONCALL' 'POINTDEFERENCING'... %%Function lo elimino
                              'CYCLOMATICCOMPLEXITY' ''...
                              }